name: ReadListenApp
options:
  bundleIdPrefix: com.readlisten
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "16.0"
  minimumXcodeGenVersion: "2.38.0"
  createIntermediateGroups: true
  defaultConfig: Debug
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "6.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    INFOPLIST_FILE: Info.plist
    PRODUCT_BUNDLE_IDENTIFIER: com.readlisten.app
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    CODE_SIGN_IDENTITY: ""
    CODE_SIGNING_REQUIRED: "NO"
    CODE_SIGNING_ALLOWED: "NO"
    GENERATE_INFOPLIST_FILE: false
  configs:
    Debug:
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
      DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
    Release:
      SWIFT_OPTIMIZATION_LEVEL: "-O"
      DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"

targets:
  ReadListenApp:
    type: application
    platform: iOS
    sources:
      - path: ReadListenApp.swift
      - path: Models
      - path: ViewModels
      - path: Views
      - path: Services
      - path: Extensions
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.readlisten.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: Info.plist
    dependencies: []
